FROM python:3.6.9-buster

COPY . /app

WORKDIR /app

ARG AWS_ACCESS_KEY_ID

ARG AWS_SECRET_ACCESS_KEY

ARG AWS_DEFAULT_REGION

ARG MONGODB_URL

ARG MLFLOW_TRACKING_URI

ARG MLFLOW_TRACKING_USERNAME

ARG MLFLOW_TRACKING_PASSWORD

ENV AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID

ENV AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY

ENV AWS_DEFAULT_REGION $AWS_DEFAULT_REGION

ENV MONGODB_URL ${MONGODB_URL}

ENV MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}}

ENV MLFLOW_TRACKING_USERNAME=${MLFLOW_TRACKING_USERNAME}

ENV MLFLOW_TRACKING_PASSWORD=${MLFLOW_TRACKING_PASSWORD}

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
